
[package]
name = "source-mesh"
version = "1.0.0"
edition = "2024"
description = "Dependency diagrams for Rust projects, powered by rust-analyzer SCIP"
license = "MIT"
readme = "README.md"
repository = "https://github.com/GeneralGDA/rust-arch"
keywords = ["rust", "dependency-graph", "architecture", "dependencies", "diagram"]
categories = ["command-line-utilities", "development-tools"]
exclude = [
    "/bin/**",
    "/target/**",
    "/work/**",
]

[[example]]
name = "regenerate-dependency-graph-scip"
path = "tools/regenerate_dependency_graph_scip.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
colorous = "1.0.16"
dunce = "1.0.5"
derive-new = "0.7"
getset = "0.1.7"
graphviz-rust = { version = "0.9.9", default-features = false }
quick-xml = "0.42.0"
scip = "0.10"
protobuf = "3.7.2"
petgraph = { version = "0.8.3", default-features = false, features = ["std"] }
same-file = "1.0.6"
serde_json = "1.0.151"
tempfile = "3.27.0"
lsp-server = "0.10.0"
url = "2.5.8"

[dev-dependencies]
pretty_assertions = "1.4.1"
roxmltree = "0.21.1"
rstest = { version = "0.27", default-features = false }

[lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
as_pointer_underscore = "deny"
as_ptr_cast_mut = "deny"
as_underscore = "deny"
bool_to_int_with_if = "deny"
borrow_as_ptr = "deny"
branches_sharing_code = "deny"
case_sensitive_file_extension_comparisons = "deny"
cast_lossless = "deny"
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_precision_loss = "deny"
cast_sign_loss = "deny"
cfg_not_test = "deny"
checked_conversions = "deny"
clear_with_drain = "deny"
clone_on_ref_ptr = "deny"
coerce_container_to_any = "deny"
collapsible_else_if = "deny"
collection_is_never_read = "deny"
comparison_chain = "deny"
copy_iterator = "deny"
create_dir = "deny"
debug_assert_with_mut_call = "deny"
decimal_bitwise_operands = "deny"
default_trait_access = "deny"
duration_suboptimal_units = "deny"
elidable_lifetime_names = "deny"
else_if_without_else = "deny"
empty_drop = "deny"
empty_enum_variants_with_brackets = "deny"
empty_enums = "deny"
empty_structs_with_brackets = "deny"
enum_glob_use = "deny"
equatable_if_let = "deny"
error_impl_error = "deny"
exit = "deny"
expect_used = "deny"
expl_impl_clone_on_copy = "deny"
explicit_into_iter_loop = "deny"
explicit_iter_loop = "deny"
fallible_impl_from = "deny"
field_scoped_visibility_modifiers = "deny"
filetype_is_file = "deny"
filter_map_next = "deny"
flat_map_option = "deny"
fn_params_excessive_bools = "deny"
fn_to_numeric_cast_any = "deny"
format_collect = "deny"
format_push_string = "deny"
get_unwrap = "deny"
host_endian_bytes = "deny"
if_not_else = "deny"
if_then_some_else_none = "deny"
ignore_without_reason = "deny"
ignored_unit_patterns = "deny"
implicit_clone = "deny"
imprecise_flops = "deny"
inconsistent_struct_constructor = "deny"
index_refutable_slice = "deny"
indexing_slicing = "deny"
infinite_loop = "deny"
integer_division = "deny"
invalid_upcast_comparisons = "deny"
ip_constant = "deny"
items_after_statements = "deny"
iter_filter_is_ok = "deny"
iter_filter_is_some = "deny"
iter_not_returning_iterator = "deny"
iter_on_empty_collections = "deny"
iter_on_single_items = "deny"
iter_over_hash_type = "deny"
iter_without_into_iter = "deny"
large_digit_groups = "deny"
large_futures = "deny"
large_stack_arrays = "deny"
large_types_passed_by_value = "deny"
let_underscore_untyped = "deny"
linkedlist = "deny"
literal_string_with_formatting_args = "deny"
lossy_float_literal = "deny"
manual_assert = "deny"
manual_ilog2 = "deny"
manual_instant_elapsed = "deny"
manual_is_power_of_two = "deny"
manual_is_variant_and = "deny"
manual_let_else = "deny"
manual_midpoint = "deny"
manual_string_new = "deny"
many_single_char_names = "deny"
map_unwrap_or = "deny"
map_with_unused_argument_over_ranges = "deny"
match_bool = "deny"
match_same_arms = "deny"
match_wild_err_arm = "deny"
match_wildcard_for_single_variants = "deny"
maybe_infinite_iter = "deny"
mismatching_type_param_order = "deny"
missing_asserts_for_indexing = "deny"
missing_const_for_fn = "deny"
mixed_read_write_in_expression = "deny"
module_name_repetitions = "deny"
multiple_inherent_impl = "deny"
must_use_candidate = "deny"
mut_mut = "deny"
naive_bytecount = "deny"
needless_bitwise_bool = "deny"
needless_collect = "deny"
needless_continue = "deny"
needless_for_each = "deny"
needless_pass_by_ref_mut = "deny"
needless_pass_by_value = "deny"
needless_raw_string_hashes = "deny"
needless_raw_strings = "deny"
needless_type_cast = "deny"
negative_feature_names = "deny"
no_effect_underscore_binding = "deny"
non_ascii_literal = "deny"
non_std_lazy_statics = "deny"
non_zero_suggestions = "deny"
nonminimal_bool = "deny"
nonstandard_macro_braces = "deny"
option_as_ref_cloned = "deny"
option_if_let_else = "deny"
option_option = "deny"
or_fun_call = "deny"
overly_complex_bool_expr = "deny"
panic_in_result_fn = "deny"
partial_pub_fields = "deny"
path_buf_push_overwrite = "deny"
pathbuf_init_then_push = "deny"
pattern_type_mismatch = "deny"
pointer_format = "deny"
precedence_bits = "deny"
ptr_as_ptr = "deny"
ptr_cast_constness = "deny"
ptr_offset_by_literal = "deny"
pub_underscore_fields = "deny"
pub_without_shorthand = "deny"
range_minus_one = "deny"
range_plus_one = "deny"
rc_buffer = "deny"
rc_mutex = "deny"
read_zero_byte_vec = "deny"
redundant_clone = "deny"
redundant_closure_for_method_calls = "deny"
redundant_else = "deny"
redundant_feature_names = "deny"
redundant_test_prefix = "allow"
ref_as_ptr = "deny"
ref_binding_to_reference = "deny"
ref_option = "deny"
ref_option_ref = "deny"
renamed_function_params = "deny"
rest_pat_in_fully_bound_structs = "deny"
return_and_then = "deny"
return_self_not_must_use = "deny"
same_functions_in_if_condition = "deny"
same_length_and_capacity = "deny"
same_name_method = "deny"
search_is_some = "deny"
self_named_module_files = "deny"
self_only_used_in_recursion = "deny"
set_contains_or_insert = "deny"
shadow_unrelated = "deny"
significant_drop_in_scrutinee = "deny"
significant_drop_tightening = "deny"
similar_names = "deny"
single_char_pattern = "deny"
single_match_else = "deny"
single_option_map = "deny"
stable_sort_primitive = "deny"
str_split_at_newline = "deny"
str_to_string = "deny"
string_add_assign = "deny"
string_slice = "deny"
struct_excessive_bools = "deny"
struct_field_names = "deny"
suboptimal_flops = "deny"
suspicious_operation_groupings = "deny"
suspicious_xor_used_as_pow = "deny"
tests_outside_test_module = "deny"
todo = "deny"
trailing_empty_array = "deny"
trait_duplication_in_bounds = "deny"
transmute_ptr_to_ptr = "deny"
transmute_undefined_repr = "deny"
trivial_regex = "deny"
trivially_copy_pass_by_ref = "deny"
try_err = "deny"
tuple_array_conversions = "deny"
type_repetition_in_bounds = "deny"
unchecked_time_subtraction = "deny"
unicode_not_nfc = "deny"
unimplemented = "deny"
uninhabited_references = "deny"
uninlined_format_args = "deny"
unnecessary_box_returns = "deny"
unnecessary_debug_formatting = "deny"
unnecessary_join = "deny"
unnecessary_literal_bound = "deny"
unnecessary_self_imports = "deny"
unnecessary_struct_initialization = "deny"
unnested_or_patterns = "deny"
unreadable_literal = "deny"
unsafe_derive_deserialize = "deny"
unseparated_literal_suffix = "deny"
unused_async = "deny"
unused_peekable = "deny"
unused_result_ok = "deny"
unused_rounding = "deny"
unused_self = "deny"
unused_trait_names = "deny"
unwrap_in_result = "deny"
unwrap_used = "deny"
use_self = "deny"
used_underscore_binding = "deny"
used_underscore_items = "deny"
useless_let_if_seq = "deny"
verbose_bit_mask = "deny"
verbose_file_reads = "deny"
volatile_composites = "deny"
while_float = "deny"
wildcard_dependencies = "deny"
wildcard_enum_match_arm = "deny"
wildcard_imports = "deny"
zero_sized_map_values = "deny"
